format = """
[ ](red)\
$username\
[](bg:green fg:red)\
$directory\
[](fg:green bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:blue)\
$python\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[ ](fg:blue)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:red"
style_root = "bg:red"
format = '[$user ]($style)'

[directory]
style = "bg:green"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = ""
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"python" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[elm]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](bg:yellow)]($style)'

[golang]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[haskell]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[julia]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[nim]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) $virtualenv ](bg:blue)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'

