format = """
[ ](fg:#9A348E)\
$username\
[](fg:#9A348E)\
$directory\
[](fg:#DA627D)\
$git_branch\
$git_status\
[](fg:#FCA17D)\
$python\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[ ](fg:#86BBD8)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#9A348E"
style_root = "fg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "fg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = ""
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"python" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[docker_context]
symbol = " "
style = "fg:#06969A"
format = '[[ $symbol $context ](fg:#06969A)]($style) $path'

[elixir]
symbol = " "
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[elm]
symbol = " "
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[git_branch]
# symbol = ""
style = "fg:#FCA17D"
format = '[[ $symbol $branch ](fg:#FCA17D)]($style)'

[git_status]
style = "fg:#FCA17D"
format = '[[($all_status$ahead_behind )](fg:#FCA17D)]($style)'

[golang]
symbol = " "
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[haskell]
symbol = " "
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[java]
symbol = " "
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[julia]
symbol = " "
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[nodejs]
symbol = ""
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[nim]
symbol = " "
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[rust]
symbol = ""
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[python]
symbol = ""
style = "fg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'
